version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  mariadb:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'cambiar'
      MYSQL_DATABASE: 'nginx'
      MYSQL_USER: 'david'
      MYSQL_PASSWORD: 'cambiar'
    volumes:
      - ./data/mysql:/var/lib/mysql
